name: CI

on: [push]

jobs:
  foundry-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install forge-std
        run: |
          forge install foundry-rs/forge-std --no-commit
          forge remappings > remappings.txt
      - name: Run non-Kontrol tests
        run: |
          forge test --no-match-path "src/test/kontrol/*" -vvv
      - name: Run snapshot without Kontrol tests
        run: forge snapshot --no-match-path "src/test/kontrol/*"

  formal-verification:
    runs-on: ubuntu-latest
    needs: foundry-test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gcc git g++ cmake maven openjdk-11-jdk flex z3 libz3-dev libsecp256k1-dev

      - name: Install KUp and Kontrol
        env:
          REPOSITORY_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
        run: |
          # Install kup without authentication
          echo "Installing kup..."
          curl -sSL https://kframework.org/install | bash
          
          # Add kup to PATH
          echo "Adding kup to PATH..."
          export PATH=$PATH:$HOME/.kup/bin
          echo "$HOME/.kup/bin" >> $GITHUB_PATH
          
          # Configure git for kup
          git config --global url."https://${REPOSITORY_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          
          # Install Kontrol with auth
          echo "Installing Kontrol..."
          export GITHUB_TOKEN=$REPOSITORY_TOKEN
          kup install kontrol
          
          # Verify installation
          echo "Verifying Kontrol installation..."
          which kontrol || { echo "kontrol not found in PATH"; exit 1; }
          kontrol --version || { echo "Kontrol installation failed"; exit 1; }

      - name: Configure Git Authentication
        env:
          REPOSITORY_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
        run: |
          echo "machine github.com login ${REPOSITORY_TOKEN}" > ~/.netrc
          chmod 600 ~/.netrc

      - name: Run Formal Verification with Kontrol
        run: |
          mkdir -p verification-results
          verified_count=0
          
          for spec in src/test/kontrol/*.k; do
            if [ -f "$spec" ]; then
              echo "Verifying $(basename "$spec")..."
              
              if kontrol prove "$spec" \
                 --contract-dir ./src/contracts \
                 --output-dir ./verification-results \
                 --verbose; then
                echo "✓ Verification successful for $spec"
                ((verified_count++))
              else
                echo "✗ Verification failed for $spec"
                cat "./verification-results/$(basename "$spec" .k).out" 2>/dev/null || echo "No output file found"
                exit 1
              fi
            fi
          done
          
          if [ $verified_count -eq 0 ]; then
            echo "No specification files found to verify"
            exit 1
          else
            echo "Successfully verified $verified_count specification(s)"
          fi