name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install forge-std
        run: |
          forge install foundry-rs/forge-std --no-commit
          forge remappings > remappings.txt
      - run: forge test -vvv
      - run: forge snapshot
  formal-verification:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Install Kontrol
        run: |
          bash <(curl https://kframework.org/install)
          kup install kontrol
      - name: Build and Run Proofs
        run: |
          kontrol build
          kontrol prove --config-profile setup
          kontrol prove --config-profile tests
      - name: View Results
        run: kontrol list