name: "[mainnet-deploy] deploy governance for vault"
on:
  workflow_dispatch:
    inputs:
      proposer:
        description: 'Proposer address'
        required: true
        default: '0x'
      vault:
        description: 'Vault Address'
        required: true
        default: '0x'
      accountant:
        description: 'Accountant Address'
        required: true
        default: '0x'
      governorRoleAddress:
        description: 'Governor role address'
        required: true
        default: '0x'
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: mainnet
      url: https://term-finance.github.io/yearn-v3-term-vault/
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: foundry-rs/foundry-toolchain@v1
      - run: forge install
      - run: forge build
      - run: forge tree
      - run: forge script script/VaultGovernanceDeploy.s.sol:VaultGovernanceDeploy --rpc-url $RPC_URL --broadcast --gas-price  500000000000   --verify --verbosity 4
        env:
          RPC_URL:  ${{ secrets.RPC_URL }}
          PRIVATE_KEY: ${{ secrets.GOVERNANCE_DEPLOYER_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          PROPOSER: ${{ github.event.inputs.proposer }}
          VAULT: ${{ github.event.inputs.vault }}
          ACCOUNTANT: ${{ github.event.inputs.accountant }}
          GOVERNOR: ${{ github.event.inputs.governorRoleAddress }}
          GOVERNANCE_FACTORY: ${{ vars.VAULT_GOVERNANCE_FACTORY }}



  